const mongoose = require("mongoose");
require("dotenv").config();

const SERVICES_DATA = [
  {
    title: "Recruitment & Staffing",
    slug: "recruitment-and-staffing",
    shortDescription: "Strategic technical and non-technical talent acquisition, flexible contract staffing, and bulk hiring designed for high-growth enterprises.",
    description: "Finding and placing the right talent is essential for scaling modern business operations. At Visha IT Solutions, our specialized recruitment and staffing services streamline candidate discovery and evaluation, connecting top-tier talent with ambitious companies across India and globally.",
    iconName: "Users",
    subServices: [
      "IT Recruitment",
      "Non-IT Recruitment",
      "Permanent Staffing",
      "Contract Staffing",
      "Contract-to-Hire",
      "Bulk Hiring",
      "Remote / Hybrid Hiring",
    ],
    features: [
      "Specialized Tech & Domain Screenings",
      "Pre-vetted Talent Bench with 48h Turnaround",
      "Contract, Permanent & Executive Search",
      "Seamless Onboarding & Documentation",
    ],
    ctaText: "Hire Talent →",
    ctaLink: "/contact",
    image: "/services/recruitment-and-staffing.jpg",
    badge: "Enterprise Staffing",
    order: 1,
    isActive: true,
  },
  {
    title: "Talent Acquisition",
    slug: "talent-acquisition",
    shortDescription: "End-to-end recruitment process outsourcing (RPO), leadership executive search, and campus placement drives tailored for modern organizations.",
    description: "Talent Acquisition is more than just filling open requisitions—it is a long-term strategic advantage. We partner directly with executive teams to anticipate hiring needs, elevate employer brand appeal, and source niche industry specialists who drive sustainable organizational growth.",
    iconName: "UserCheck",
    subServices: [
      "End-to-End RPO Solutions",
      "Executive & Leadership Search",
      "Campus Hiring & Drive Management",
      "Employer Branding Consulting",
      "Diversity & Inclusion Recruitment",
      "Talent Pipeline Development",
    ],
    features: [
      "Dedicated Client Talent Partner",
      "Confidential C-Suite Headhunting",
      "Comprehensive Competency Mapping",
      "Structured Multi-Round Technical Audits",
    ],
    ctaText: "Acquire Talent →",
    ctaLink: "/contact",
    image: "/services/talent-acquisition.jpg",
    badge: "Executive Search",
    order: 2,
    isActive: true,
  },
  {
    title: "Payroll & HR Services",
    slug: "payroll-and-hr-services",
    shortDescription: "Flawless automated salary disbursements, statutory compliance management (PF, ESI, TDS), and complete employee lifecycle infrastructure.",
    description: "Managing corporate payroll and complex regulatory compliance requires meticulous precision and unwavering security. Visha IT Solutions delivers fully managed HR operations that eradicate compliance risk, automate tax calculations, and provide transparent self-service experiences for your entire workforce.",
    iconName: "FileSpreadsheet",
    subServices: [
      "Automated Payroll Processing",
      "Statutory Compliance (PF, ESI, PT, TDS)",
      "Leave & Attendance Systems",
      "Employee Lifecycle Documentation",
      "HR Policy Formulation & Audits",
      "Year-End Tax Declarations & Form 16",
    ],
    features: [
      "Zero-Error Automated Calculation Engine",
      "100% On-Time Statutory Filings",
      "Encrypted Cloud Employee Self-Service",
      "Scalable for 10 to 10,000+ Employees",
    ],
    ctaText: "Manage Payroll →",
    ctaLink: "/contact",
    image: "/services/payroll-and-hr-services.jpg",
    badge: "Compliant HR",
    order: 3,
    isActive: true,
  },
  {
    title: "Digital Marketing",
    slug: "digital-marketing-services",
    shortDescription: "High-ROI digital growth strategies spanning technical SEO, high-conversion PPC campaigns, social media marketing, and automated lead funnels.",
    description: "In an increasingly competitive digital marketplace, generic advertising yields diminishing returns. We architect hyper-targeted, data-driven marketing campaigns that captivate high-intent prospects, lower cost-per-acquisition (CPA), and maximize long-term customer lifetime value (LTV).",
    iconName: "Megaphone",
    subServices: [
      "Search Engine Optimization (SEO)",
      "Pay-Per-Click Advertising (Google / Meta)",
      "Social Media Marketing & Brand Growth",
      "Content Marketing & Copywriting",
      "Email Marketing & Automation Funnels",
      "Conversion Rate Optimization (CRO)",
    ],
    features: [
      "Targeted Multi-Channel Funnel Architecture",
      "Weekly Data-Driven Optimization Sprints",
      "Transparent Real-Time ROI Analytics",
      "A/B Tested Creative & Ad Copy",
    ],
    ctaText: "Grow Online →",
    ctaLink: "/contact",
    image: "/services/digital-marketing-services.jpg",
    badge: "Growth Marketing",
    order: 4,
    isActive: true,
  },
  {
    title: "E-Commerce Solutions",
    slug: "ecommerce-solutions",
    shortDescription: "Enterprise digital storefront engineering, seamless payment gateway integrations, catalog optimizations, and omnichannel fulfillment setup.",
    description: "Your digital storefront is the flagship anchor of your global brand. We build blazing-fast, secure, and infinitely scalable e-commerce ecosystems utilizing modern headless frameworks, Shopify Plus, and custom microservice backends engineered for peak holiday flash sales.",
    iconName: "ShoppingCart",
    subServices: [
      "Custom E-Commerce Storefront Development",
      "Shopify & WooCommerce Engineering",
      "Payment Gateway Integration",
      "Multi-Warehouse Inventory Sync",
      "Mobile-First Shopping Experiences",
      "Marketplace Integration (Amazon, Flipkart)",
    ],
    features: [
      "Sub-Second Global Page Load Speeds",
      "Multi-Currency & International Tax Setup",
      "Frictionless One-Click Checkout Flows",
      "Enterprise Grade PCI-DSS Security",
    ],
    ctaText: "Launch Store →",
    ctaLink: "/contact",
    image: "/services/ecommerce-solutions.jpg",
    badge: "Digital Commerce",
    order: 5,
    isActive: true,
  },
  {
    title: "Training & Career Development",
    slug: "training-and-career-development",
    shortDescription: "Job-oriented full-stack technical programs, corporate upskilling workshops, hands-on production labs, and 100% interview placement support.",
    description: "Bridging the persistent divide between theoretical university coursework and real-world software engineering expectations. Our immersive training tracks are mentored by practicing senior tech architects, equipping candidates with production-grade problem-solving skills.",
    iconName: "GraduationCap",
    subServices: [
      "Full-Stack Software Engineering Tracks",
      "Corporate Team Upskilling Workshops",
      "Live Production Project Internships",
      "Data Structures & System Design Labs",
      "Resume Re-Engineering & Mock Interviews",
      "Guaranteed Placement Referral Drives",
    ],
    features: [
      "1:1 Senior Engineering Mentorship",
      "Production-Grade GitHub Capstones",
      "Rigorous Algorithmic & Interview Prep",
      "Direct Referrals to 500+ Hiring Partners",
    ],
    ctaText: "Explore Courses →",
    ctaLink: "/training",
    image: "/services/training-and-career-development.jpg",
    badge: "Career Academy",
    order: 6,
    isActive: true,
  },
];

const PROJECTS_DATA = [
  {
    title: "Global E-Commerce Platform",
    slug: "global-ecommerce-platform",
    clientName: "RetailCorp International",
    category: "E-Commerce & Omnichannel",
    badge: "+45% Conversion Surge",
    shortDescription: "A high-concurrency digital commerce engine engineered for global operations, handling 10k+ concurrent shoppers with sub-second page performance.",
    description: "RetailCorp International required an enterprise digital commerce overhaul to replace fragmented regional store platforms with a unified, cloud-native commerce ecosystem across 12 countries.\n\nOur team architected a headless Next.js frontend integrated with high-throughput Node.js microservices, MongoDB Atlas multi-region clusters, and Redis caching. We implemented multi-currency checkout via Stripe API, real-time inventory synchronization across warehouse hubs, and automated tax calculations. The new platform handles over 10,000 peak concurrent users during holiday flashes with 99.99% uptime and reduced page load latencies to under 800 milliseconds.",
    image: "/services/ecommerce-solutions.jpg",
    technologies: ["Next.js 15", "Node.js", "MongoDB Atlas", "Redis", "Stripe API", "AWS CloudFront", "Tailwind CSS"],
    metrics: ["+45% Conversion Rate", "99.99% Cloud Uptime", "<800ms Page Latency", "10k+ Peak Concurrent Orders"],
    deliverables: [
      "Headless Storefront with Sub-Second Global CDN",
      "Real-Time Multi-Warehouse Inventory Sync",
      "Multi-Currency & Localized Payment Gateways",
      "Elastic Auto-Scaling Infrastructure on AWS",
    ],
    outcome: "Increased conversion rates by 45% while reducing server operating overhead by 32% within the first 6 months of launch.",
    order: 1,
    featured: true,
    isActive: true,
  },
  {
    title: "FinTech Analytics Dashboard",
    slug: "fintech-dashboard",
    clientName: "SecureBank Financial Group",
    category: "Financial Technology & Banking",
    badge: "Zero-Latency Feeds",
    shortDescription: "Institutional wealth management and risk modeling portal tracking $2.4B+ in daily institutional transactions with PCI-DSS compliance.",
    description: "SecureBank needed a modern financial intelligence portal capable of synthesizing high-frequency transactional data into actionable predictive insights for asset managers and compliance officers.\n\nWe engineered a resilient single-page application built on React, TypeScript, and high-performance Python FastAPI microservices connected to Apache Kafka event pipelines and time-series databases. The portal features role-based access control, automated AML (Anti-Money Laundering) fraud detection triggers, and SEC regulatory export compliance.",
    image: "/services/digital-marketing-services.jpg",
    technologies: ["React", "TypeScript", "Python FastAPI", "PostgreSQL", "Apache Kafka", "Docker", "Tailwind CSS"],
    metrics: ["$2.4B+ Daily Transactions Tracked", "100% SEC/PCI-DSS Compliance", "4x Faster Audit Turnaround", "<50ms Real-Time Data Push"],
    deliverables: [
      "Sub-Millisecond Financial Stream Visualization",
      "Automated Regulatory & Tax Reporting Engine",
      "Multi-Tier Role & Compliance Permission Matrix",
      "Predictive Machine Learning Risk Assessment Model",
    ],
    outcome: "Accelerated compliance audit preparation by 75% and enabled instantaneous risk mitigation across global client portfolios.",
    order: 2,
    featured: true,
    isActive: true,
  },
  {
    title: "Healthcare Telemedicine Portal",
    slug: "healthcare-booking-system",
    clientName: "MediCare Health Network",
    category: "Healthcare & MedTech",
    badge: "HIPAA Certified",
    shortDescription: "HIPAA-compliant telemedicine and patient scheduling ecosystem serving 150k+ active patients across 24 specialty clinical branches.",
    description: "MediCare Health Network sought to bridge physical clinic visits with high-definition digital healthcare consultations through an integrated patient engagement platform.\n\nWe designed and implemented a HIPAA-compliant platform with WebRTC end-to-end encrypted video consultations, electronic health record (EHR) integration, automated appointment scheduling with SMS/WhatsApp notifications, and secure digital prescription dispatch. The platform has successfully facilitated over 150,000 digital consultations with an unprecedented 98.7% patient satisfaction rating.",
    image: "/services/talent-acquisition.jpg",
    technologies: ["Next.js", "WebRTC", "Express.js", "MongoDB", "AWS HIPAA Cloud", "Socket.io", "Twilio API"],
    metrics: ["150k+ Consultations Completed", "85% Reduced Clinic Wait Times", "98.7% Patient Satisfaction", "100% HIPAA Data Encryption"],
    deliverables: [
      "End-to-End Encrypted WebRTC Video Consultation",
      "Centralized Electronic Health Records (EHR) Integration",
      "Automated Multilingual SMS/Email Appointment Reminders",
      "Digital Prescription & Lab Report Portal",
    ],
    outcome: "Decreased average patient wait times by 85% and expanded patient service reach into regional and remote communities.",
    order: 3,
    featured: true,
    isActive: true,
  },
  {
    title: "Logistics & Supply Chain ERP",
    slug: "logistics-erp",
    clientName: "FastTrack Global Logistics",
    category: "Logistics & Supply Chain",
    badge: "Fleet Telematics",
    shortDescription: "End-to-end enterprise supply chain suite managing 1,200+ fleet vehicles, automated route dispatching, and multi-hub warehouse inventories.",
    description: "FastTrack Logistics operates across challenging multi-modal supply corridors. They required a modern enterprise resource planning (ERP) system to replace disparate legacy software and gain real-time visibility into fleet operations.\n\nOur engineering team developed a unified platform utilizing ASP.NET Core Web API, Angular, and Microsoft Azure IoT Hub. The solution connects GPS telematics from over 1,200 vehicles, computes optimal delivery routes dynamically to conserve fuel, and automates customs manifest generation across interstate borders.",
    image: "/services/recruitment-and-staffing.jpg",
    technologies: [".NET Core 9", "Angular", "Microsoft SQL Server", "Azure IoT Hub", "PowerBI", "Docker"],
    metrics: ["38% Fewer Delivery Delays", "1,200+ Active Fleet Units", "15k+ Daily Waybills Processed", "$1.8M Annual Fuel Savings"],
    deliverables: [
      "Automated Fleet Route Optimization Engine",
      "Multi-Hub Warehouse Inventory & Barcode Tracking",
      "Real-Time Telematics & Fuel Efficiency Analytics",
      "Instant Electronic Proof-of-Delivery (e-POD)",
    ],
    outcome: "Reduced fleet fuel expenditure by $1.8M annually and eliminated dispatch scheduling bottlenecks by 65%.",
    order: 4,
    featured: false,
    isActive: true,
  },
  {
    title: "Enterprise HRMS & Payroll Cloud",
    slug: "corporate-hr-portal",
    clientName: "Apex Corporate Holdings",
    category: "Enterprise HR & Payroll",
    badge: "Statutory Compliance",
    shortDescription: "Unified workforce management, attendance tracking, and compliant payroll cloud handling 50,000+ monthly disbursements.",
    description: "Apex Holdings manages diverse operating subsidiaries with varying compensation structures and compliance requirements. They partnered with Visha IT Solutions to build a centralized, audit-ready Human Resources Management System.\n\nWe engineered a secure cloud portal that automates salary processing, tax deductions (TDS, PF, ESI), geo-tagged mobile attendance, and performance appraisals. The platform includes self-service portals for employees to access payslips and tax worksheets, backed by robust encryption and disaster recovery protocols.",
    image: "/services/payroll-and-hr-services.jpg",
    technologies: ["React", "Node.js", "PostgreSQL", "Docker", "AWS S3", "Redis", "Tailwind CSS"],
    metrics: ["50k+ Monthly Payrolls Processed", "Zero Statutory Penalty Record", "92% Drop in Employee HR Tickets", "100% On-Time Salary Payouts"],
    deliverables: [
      "One-Click Automated Multi-Tier Salary Disbursements",
      "Dynamic Geo-Fenced Mobile Attendance Tracking",
      "Employee Self-Service (ESS) Document Vault",
      "Audit-Ready Statutory Tax Reporting & Form 16",
    ],
    outcome: "Reduced monthly payroll reconciliation time from 7 days to under 3 hours, achieving 100% regulatory compliance accuracy.",
    order: 5,
    featured: false,
    isActive: true,
  },
  {
    title: "Omni-Channel AI Support Agent",
    slug: "ai-customer-support-bot",
    clientName: "OmniTech Global Solutions",
    category: "Artificial Intelligence & Automation",
    badge: "Autonomous AI",
    shortDescription: "Generative AI conversational support agent delivering 24/7 multilingual ticket resolution with automated CRM synchronization.",
    description: "OmniTech Global sought to alleviate customer support queues across email, web chat, and WhatsApp without sacrificing satisfaction quality.\n\nOur AI engineering team deployed an autonomous conversational agent powered by OpenAI GPT-4o, LangChain, and a vector database of OmniTech's knowledge base. The agent handles tiered inquiries, accurately diagnoses technical issues, processes return requests, and escalates complex edge cases to human specialists with synthesized conversation summaries.",
    image: "/services/website-development.jpg",
    technologies: ["Python", "FastAPI", "LangChain", "OpenAI API", "Pinecone Vector DB", "React", "WebSockets"],
    metrics: ["82% First-Contact Resolution Rate", "<10s Average Response Time", "4.8/5 Customer Satisfaction", "60% Support Cost Reduction"],
    deliverables: [
      "Vector-Indexed Dynamic Knowledge Base Agent",
      "Multilingual Natural Language Processing (20+ Languages)",
      "Seamless Live CRM & Zendesk Ticket Sync",
      "Sentiment-Triggered Human Escalation Workflow",
    ],
    outcome: "Resolved 82% of customer inquiries autonomously while decreasing average response latency from 45 minutes to under 10 seconds.",
    order: 6,
    featured: false,
    isActive: true,
  },
];

const TRAINING_DATA = [
  {
    title: "Python Full Stack Development",
    slug: "python-full-stack",
    badge: "Most Popular",
    shortDescription: "Master end-to-end web engineering with Python 3.12, Django 5, FastAPI, modern React, and PostgreSQL through hands-on enterprise projects.",
    description: "Our Python Full Stack Development program is built from the ground up to transform aspiring developers into production-ready engineers. You will start with core Python programming, object-oriented concepts, and advanced asynchronous programming. You'll master scalable backend architectures using Django and high-performance FastAPI microservices, alongside modern relational databases (PostgreSQL) and caching layers (Redis).\n\nOn the frontend, you'll gain expertise in React.js, modern JavaScript/TypeScript, and responsive UI design with Tailwind CSS. Throughout the course, you'll architect real-world capstone projects, implement Docker containers, configure CI/CD pipelines, and prepare for rigorous technical interviews with top-tier hiring partners.",
    duration: "6 Months",
    mode: "Hybrid (Online + Lab)",
    level: "Beginner to Enterprise",
    technologies: ["Python 3.12", "Django 5", "FastAPI", "React.js", "PostgreSQL", "Pandas", "Docker", "Git"],
    syllabus: [
      "Core & Advanced Python (OOP, AsyncIO, Generators)",
      "Web Frameworks: Django & FastAPI Asynchronous APIs",
      "Relational & NoSQL Databases: PostgreSQL & Redis",
      "Modern Frontend: React.js, Hooks & Tailwind CSS",
      "Data Science, Automation & Web Scraping",
      "Docker, Cloud Deployment & Enterprise Capstone",
    ],
    careerRoles: [
      "Full Stack Python Engineer",
      "Python Backend Developer",
      "FastAPI / Django Specialist",
      "Software Development Engineer (SDE)",
    ],
    image: "/services/training-and-career-development.jpg",
    order: 1,
    isActive: true,
  },
  {
    title: "MERN Stack Development",
    slug: "mern-stack-development",
    badge: "High Demand",
    shortDescription: "Build high-concurrency modern web apps using MongoDB, Express.js, React.js 19, Node.js, Next.js, and TypeScript with real-time features.",
    description: "The MERN stack powers modern web startups and Fortune 500 enterprises alike. This comprehensive masterclass covers modern JavaScript (ES6+), TypeScript, server-side development with Node.js and Express, and robust database design using MongoDB Atlas.\n\nYou will master component architecture with React 19, server-side rendering with Next.js App Router, state management with Redux Toolkit, and real-time socket communications. You will build and deploy an enterprise-grade collaborative application from scratch, complete with automated testing and cloud deployment on AWS.",
    duration: "6 Months",
    mode: "Hybrid",
    level: "Beginner to Pro",
    technologies: ["MongoDB", "Express.js", "React 19", "Node.js", "Next.js", "TypeScript", "AWS"],
    syllabus: [
      "Module 1: JavaScript & Web Foundations – HTML, CSS, and modern JavaScript (ES6+)",
      "Module 2: Node.js & Express.js – Setting up servers and building REST APIs",
      "Module 3: MongoDB & Mongoose – Managing NoSQL databases and schemas",
      "Module 4: React.js – Building front-end components, hooks, and state management",
      "Module 5: Full-Stack Integration & Auth – Connecting frontend to backend, JWT/cookies security",
      "Module 6: Deployment & Projects – Launching live apps on Render, Vercel, or AWS",
    ],
    careerRoles: [
      "MERN Stack Developer",
      "Frontend React Engineer",
      "Node.js Backend Developer",
      "Full Stack Web Engineer",
    ],
    image: "/services/website-development.jpg",
    order: 2,
    isActive: true,
  },
  {
    title: ".NET Full Stack Development",
    slug: "dotnet-full-stack",
    badge: "Enterprise Choice",
    shortDescription: "Enterprise systems engineering with C#, ASP.NET Core 9 Web API, Entity Framework Core, Angular/React, Microsoft SQL Server, and Microsoft Azure.",
    description: "Enterprise corporations rely on the Microsoft .NET ecosystem for mission-critical reliability and performance. This course provides comprehensive training in C# 13, object-oriented design patterns, and ASP.NET Core 9 Web API development.\n\nYou will master Entity Framework Core, database query optimization with SQL Server, microservices architecture, and modern single-page applications using Angular or React. Learn to package, test, and deploy enterprise applications seamlessly to Microsoft Azure using Azure DevOps CI/CD pipelines.",
    duration: "5 Months",
    mode: "Online & Classroom",
    level: "Intermediate to Enterprise",
    technologies: ["C# 13", ".NET Core 9", "ASP.NET Web API", "Entity Framework", "SQL Server", "Azure", "Angular/React"],
    syllabus: [
      "Module 1: C# Programming Language – Syntax, OOP, Async/Await & LINQ",
      "Module 2: .NET Core & ASP.NET Core – Web APIs, MVC, DI & Middleware",
      "Module 3: Data Access & Databases – Entity Framework Core & SQL Server",
      "Module 4: Frontend Integration – Angular or React with .NET Web APIs",
      "Module 5: DevOps, Cloud & Testing – Unit Testing, Docker & Azure Deployment",
    ],
    careerRoles: [
      ".NET Full Stack Engineer",
      "C# Backend Specialist",
      "Enterprise Solutions Developer",
      "Microsoft Cloud Consultant",
    ],
    image: "/services/ecommerce-solutions.jpg",
    order: 3,
    isActive: true,
  },
];

async function sync() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log("Connected to MongoDB successfully!");

  const db = mongoose.connection.db;

  // 1. Sync Services
  console.log("Syncing Services...");
  await db.collection("services").deleteMany({});
  const serviceResult = await db.collection("services").insertMany(SERVICES_DATA);
  console.log(`Inserted ${serviceResult.insertedCount} Services into MongoDB!`);

  // 2. Sync Projects
  console.log("Syncing Projects...");
  await db.collection("projects").deleteMany({});
  const projectResult = await db.collection("projects").insertMany(PROJECTS_DATA);
  console.log(`Inserted ${projectResult.insertedCount} Projects into MongoDB!`);

  // 3. Sync Training Programs
  console.log("Syncing Training Programs...");
  await db.collection("trainingprograms").deleteMany({});
  const trainingResult = await db.collection("trainingprograms").insertMany(TRAINING_DATA);
  console.log(`Inserted ${trainingResult.insertedCount} Training Programs into MongoDB!`);

  console.log("ALL COLLECTIONS SYNCHRONIZED PERFECTLY!");
  await mongoose.disconnect();
}

sync().catch(console.error);
